{{- if .Values.deployment }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
{{ include "application.labels.stakater" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{- if .Values.deployment.additionalLabels }}
{{ toYaml .Values.deployment.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.deployment.annotations }}
  annotations:
{{ toYaml .Values.deployment.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" . }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  {{- if .Values.deployment.strategy }}
  strategy:
{{ toYaml .Values.deployment.strategy | indent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
{{ include "application.labels.stakater" . | indent 8 }}
{{ include "application.labels.chart" . | indent 8 }}
{{- if .Values.deployment.additionalPodLabels }}
{{ toYaml .Values.deployment.additionalPodLabels | indent 8 }}
{{- end }}
{{- if .Values.deployment.podLabels }}
{{ toYaml .Values.deployment.podLabels | indent 8 }}
{{- end }}
{{- if or .Values.deployment.additionalPodAnnotations .Values.deployment.fluentdConfigAnnotations }}
      annotations:
{{- end }}
{{- with .Values.deployment.additionalPodAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- if .Values.deployment.fluentdConfigAnnotations }}
        fluentdConfiguration: >
          [
            {
              "containers":
              [
                {
                  "expressionFirstLine": "{{ .Values.deployment.fluentdConfigAnnotations.regexFirstLine }}",
                  "expression": "{{ .Values.deployment.fluentdConfigAnnotations.regex }}",
                  "timeFormat": "{{ .Values.deployment.fluentdConfigAnnotations.timeFormat }}",
                  "containerName": "{{ template "application.name" . }}"
                }
              ]{{- with .Values.deployment.fluentdConfigAnnotations.notifications }},
              "notifications": {
                {{- with .slack }}
                "slack": {
                  "webhookURL": "{{ .webhookURL }}",
                  "channelName": "{{ .channelName }}"
                }
                {{- end }}
              }
              {{- end }}
            }
          ]
{{- end }}
    spec:
      {{- if .Values.deployment.initContainers }}
      initContainers:      
{{ toYaml .Values.deployment.initContainers | indent 6 }}
      {{- end }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.deployment.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.deployment.tolerations }}
      tolerations:
{{ toYaml .Values.deployment.tolerations | indent 8 -}}
      {{- end }}
      {{- if .Values.deployment.imagePullSecrets }}      
      imagePullSecrets:
      - name: {{ .Values.deployment.imagePullSecrets }}
      {{- end }}
      containers:
      - name: {{ template "application.name" . }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        {{- if .Values.deployment.env }}
        env:
{{ toYaml .Values.deployment.env | indent 10 }}
        {{- end }}          
        {{- with .Values.deployment.probes }}
{{ toYaml . | indent 8 }}
        {{- end }}
        {{- if .Values.deployment.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.deployment.volumeMounts | indent 10 }}
        {{- end }}                
        {{- with .Values.deployment.resources }}
        resources:
{{ toYaml . | indent 10 }}
        {{- end }}
        {{- if .Values.deployment.additionalContainers }}
{{ toYaml .Values.deployment.additionalContainers | indent 6 }}
        {{- end }}
        {{- if .Values.deployment.securityContext }}
      securityContext:      
{{ toYaml .Values.deployment.securityContext | indent 8 }}
          {{- end }}
      {{- if .Values.deployment.volumes }}
      volumes:
{{ toYaml .Values.deployment.volumes | indent 8 }}
        {{- end }}  
      {{- if .Values.rbac.serviceAccount.name }}
      serviceAccountName: {{ .Values.rbac.serviceAccount.name }}
        {{- else }}
      serviceAccountName: {{ template "application.name" . }}
      {{- end }}
{{- end }}        